### ISSUE TITLE
Steering Committee Photos

### ISSUE THREAD

**Issue by ababaian** [hackseq/October_2016#1]
Please upload a photo of yourself for your icon (at least 1000x1000) and write down how you want your affiliation written.

see: [~/website/steeringCommittee_photos/readme](https://github.com/hackseq/October_2016/blob/master/website/steeringCommittee_photos/README.md)
- [x] Artem Babaian. Webmaster
- [x] Britt Drogemoller. Team Leaders liason
- [x] Bruno Grande. Logistics
- [x] Shaun Jackman. Computing/Team Forming
- [x] Amy Lee. Public relations/Communications
- [x] Santina Lin. Participants liason
- [x] Catrina Loucks. Team Leaders liason
- [x] Adriana Suarez-Gonzalez. President/Founder
- [x] Tiffany Timbers. Public relations/Secretary
- [x] Galen Wright. Public relations

**Comment by adrisua** [comment]
@hackseq/steering_committee 
Let's include our roles:

Artem Babaian. Webmaster
Britt Drogemoller. Team Leaders liason
Bruno Grande. Logistics
Shaun Jackman. Computing/Team Forming
Amy Lee. Public relations/Communications
Santina Lin. Participants liason
Catrina Loucks. Team Leaders liason
Adriana Suarez-Gonzalez. President/Founder
Tiffany Timbers. Public relations/Secretary
Galen Wright. Public relations

*If you have any objections please let us know by March 22
@ababaian would you mind posting them then.
Thanks!

**Comment by ababaian** [comment]
@hackseq/steering_committee
I'm just thinking out loud and feel free to disagree. If we want to be a organization that promotes collaboration and not personal ownership of science then we should consider how the running of the organization can reflect that. Can everyone be viewed as equal 'co-founders' from the beginning.

That being said I think it's important to have a some oversight/leadership, someone responsible for the greater organization, thus we should elect a President/Chair (w/e the title is). I think the obvious choice is Adriana but it should be open for nominations and ballot if we go that way.

It may be silly/symbolic at this point and we all know who will be the leader, but I think it'll be important for us to figure out what (if any) social objectives we would like to pursue and how we can reflect those values in hackseq.

Related to this I've written a little bit on the [Our Philosophy](http://www.hackseq.com/our-philisophy/) page. Hopefully we all agree on it. Maybe for the next in-person meeting we can all come with some ideas of what social goals we would like to focus on and expand that a bit?

edit:In [1971 some outdoor club students at UBC started Mountain Equipment Co-op](http://www.theglobeandmail.com/report-on-business/mec-governance-changes-sparks-dissent-among-long-time-loyalists/article26852082/) to buy/sell cheap gear from the states to other students. Of course MEC is a different beast these days but there might be a lesson in it. A co-op structure might work for something like hackseq?

2c

**Comment by adrisua** [comment]
Thank you for sharing your thoughts @ababaian  
Just to give everyone some context.  
The 3-day Genomics Hackathon in Vancouver was born in fall 2015 as part of my work as Director of events at SCWIST. The main driver was to create a space for both women and men, where they could collaborate to create new tools for omics analysis. In October 2015, I submitted a proposal to Genome BC. In November 2015, I connected with NCBI, which supported the idea and provided guidance. They also suggested me to connect with the ASHG. In December, Tiffany came on board and in January I sent the first formal proposal to the ASHG (I’ve submitted 2 more since then). In February, ECOSCOPE came on board and on March 15th we had the first committee meeting, spearheaded by @ttimbers. Besides all of these successful connections, there have also been other dead ends of course. 
As you can imagine, this has been the product of many hours of work (sometimes even +15 h a week) and a possibility thanks to people that believed in this project since it was a team of 1. It will be a reality, thanks to all of you and your amazing ideas!
If we were to use the word Co-founder, it will go to @ttimbers. She supported the idea since its early stages – let’s do that :)
@ababaian what you propose about co-ops and organizations it is great, and already an item on the agenda for our meeting in May.  
For now, we are discussing and planning the first Vancouver Genomics Hackathon, now called hackseq.  
Thanks for bringing up the Philosophy section here, it is definitely something we should discuss as a group. For example, we should include the initial driver, which was to create an inclusive place for everyone (*with coding experience). 
I also wanted to note that this event is different to the one @ababaian envisioned on the weekend of the hatchhealth hackathon (March 12-13), which I think is really cool and should happen. That is something we could discuss in the future. 
Here is my new proposal:
Artem Babaian. Webmaster
Britt Drogemoller. Team Leaders liaison
Bruno Grande. Logistics
Shaun Jackman. IT/Team Forming
Amy Lee. Public relations/Communications
Santina Lin. Participants liaison
Catrina Loucks. Team Leaders liaison
Adriana Suarez-Gonzalez. President/Co-Founder
Tiffany Timbers. VP/Co-Founder
Galen Wright. Public relations
If people are interested in discussing this further (roles), I've scheduled a skype meeting on Monday at 5:30 pm. Thanks!

**Comment by ababaian** [comment]
@adrisua I didn't mean to minimize your contributions, my question was more "What's the objective?" and how can organizational structure reflect that. 

It largely seems like it's my misconception, is the focus on a single hackathon in October, annual hackathons, or more? Are we trying to start a community for biohackers to collaborate in Vancouver or internationally? I think having a well defined objective is important for an organization.

If it's slated to be discussed in May then that's perfect.

**Comment by sjackman** [comment]
We're all founding members, since this is the first HackSeq, but the role of founding director/president falls to Adriana and Tiffany.

**Comment by ttimbers** [comment]
I suggest all of us are members of the Steering committee/Development team/whatever we want to call it. I also do not think that we need "titles". At the last meeting, the jobs were divided up so that we would would be able to get some work done, essentially so we could divide and conquer all necessary tasks. I think for making decisions, we are all equals and we can simply vote on anything that's needs to be decided by the group. 

As for the title founder/co-founder/founding director/president, I do not think that I deserve such a title. Before our last meeting I had simply been helping @adrisua get this off the ground, but she really put in all the hard work to generate this idea, get this thing started, and get some serious funding.

Finally, as for making a plan for the hackseq organization, I think we are putting the cart before the horse. We haven't even launched this plane for the October event we are planning. Let's get this thing launched and landed, and then we can discuss where to go from there. 

Again, we can discuss this all further at our all May meeting, but until then, let's leave the roles & the organizational philosophy/manifesto off the website until we've had time as a committee to discuss it in person. We have lots of other things to focus on until then.

**Comment by ttimbers** [comment]
Re: all we have discussed in these threads about titles/philosophy/founder, there is now an agenda started [here](https://github.com/hackseq/October_2016/blob/master/meeting_notes/Agenda_May.md).  I will now close this issue and if you want to discuss any of these things at the next meeting (or anything else!), please add them to the agenda. cc @ababaian @adrisua @sjackman @minisciencegirl

**Comment by minisciencegirl** [comment]
Thank you @ttimbers. I concur with your thoughts on job description and the hackseq organization.

**Comment by sjackman** [comment]
Well put, Tiffany. I agree.

**Comment by ababaian** [comment]
I concur; but the original issue is still open: I need photos of all of you! <3

**Comment by ababaian** [comment]
I concur w/ Tiffany; we can deal with this later.

That being said I still need photos uploaded from: @brunogrande @minisciencegirl @santina @cloucks 

Aand @sjackman, the photo you provided is a bit too narrow; the icons are circular, could you provide a photo that's a bit wider?

**Comment by sjackman** [comment]
Fixed in bd7660675698203b22c51be3fbe0f8005b73ba06

**Comment by adrisua** [comment]
Funny how something can be simple and complex at the same time. The driver to start this conversation was the application for sponsorship I am sending out to organizations, which in some cases require to state roles/and or the person leading the event. 
Titles or no titles, this is a really exciting project and it is wonderful to be part of such an awesome team! It has been and I'm sure will keep being a learning experience (not related to this issue, but just wanted to share that :smile:)

**Comment by BrunoGrandePhD** [comment]
Done in d8d032e.

**Comment by DCGenomics** [comment]
I might have mentioned this before, but I would also suggest getting a <librarian> to help with writing articles to advertise the software piece of things.  Perhaps there is a medical librarian or similar at UBC or SFU?  If no one comes to mind, Ill be at the medical librarian association meeting in Toronto next month and can ask around.

Please advise.

**Comment by ababaian** [comment]
Having a dedicated 'documenter' may be an idea. Have people with specifically strong writing skills join each team.

Related to this, we should consider a head writer (maybe on the committee) to write a [meeting report for publication](http://jbiomedsem.biomedcentral.com/articles/10.1186/2041-1480-1-8)
