### ISSUE TITLE
Participants application

### ISSUE THREAD

**Issue by sjackman** [hackseq/October_2016#14]
For reference:
https://docs.google.com/forms/d/19dXK7tkGZ6hoyZLZxbnyqLsTNVZDKUQGBxrz1dmYpHg/viewform

Application for Participation in Advanced Genomics Hackathon (Boston)
- What is the primary research question you work on?
- Do you have a working knowledge of shell scripting?
- Do you use any other programming languages?
- Please tell us in 3-4 sentences why you want to participate.
- What is your name?
- Have you ever done any genomic analysis on a command line? (or many analyses in a framework such as Galaxy)
- Are you interested in working on a similar problem during this workshop?
- Here are Some Approximate Project Titles (which are expected to evolve); which are you interested in working on? Please check all that apply; note that "*" indicates the project is open to anyone with some coding skills, regardless of genomics experience, particularly librarians and front-end developers.
- What is your email address?
- What is your approximate geographic location?

**Comment by DCGenomics** [comment]
Happy to share the original doc with the group.

Cheers!
Ben

**Comment by santina** [comment]
I guess that, for our purpose, this application would also include choices of their favorite projects once those are finalized. 

Btw, Thank you @DCGenomics  (Ben)!  :)

**Comment by adrisua** [comment]
@santina would you mind reminding me, when are you planning to send a draft of the participants applications to the team?

**Comment by santina** [comment]
@adrisua I just realize something: Is this the 1) interest one or the 2) actual application ? 
1) This won't need all the details, but just their email so we can contact them when the application opens. 
2) I can make one this week, going with the content in the first comment, and have a placeholder for the favorite projects checklist since we don't have that info yet.

**Comment by adrisua** [comment]
Sounds good! Thanks @santina

**Comment by santina** [comment]
Dear all, here is the [first version](https://docs.google.com/forms/d/19rgCe3vTARspXwUWaOWeOSQJ8wKyl0NhpmIEAtPexNg/viewform?entry.1646382770&entry.182572379&entry.74895983&entry.697730621&entry.992601766) of the participant form. Please comment if you have any suggestions/thoughts for changes. Thanks!

**Comment by ttimbers** [comment]
@santina should we ask them if they are familiar with version control and remote/high-performance computing?

**Comment by DCGenomics** [comment]
Just a couple of notes from NCBI Hackathon experiences:

In terms of versioning, we ask all accepted applicants for a github user
name.  This might be something that could be added to the application, but
about 1/3 of qualified applicants don't already have github accounts, so
that may cause some drop off.

As for hpc, we do most of that for the attendees.  Usually, one person in
each group is designated a sysadmin and deals with communicating capacity
and other issues to the tech lead.

Please let me know if these notes are helpful, and if you have any
comments.  Always looking to iterate.

**Comment by ttimbers** [comment]
+1 to asking for github user name. A definite must for team leaders (since we require the projects to be open source), and a good way to help screen for participants.

**Comment by adrisua** [comment]
It looks great @santina! 
I just got great news from the ASHG. They have approved up to $4,500 (or 3 travel grants) for hackseq participants! Woohoo!! There are some stipulations, however:
Each recipient must be:
1. A trainee (e.g., a graduate student or post-doc)
2. A member of ASHG (membership number required)
3. Registered for the 2016 ASHG Annual Meeting in Vancouver

Would you mind adding the following questions?:
- Do you require a travel grant to participate?
  If yes, ask if they fulfill the requirements above to apply for one
- Why would you like to participate in hackseq?
- How did you hear about hackseq? Options (Twitter, Facebook, email, friend...etc)

**Comment by ttimbers** [comment]
Fantastic news about the travel awards from ASHG!!!

**Comment by adrisua** [comment]
@santina If there are more than three participants that fulfill the requirements, what would be the factors we will be taking into consideration for giving out the awards? 
cc: @hackseq/steering_committee

**Comment by santina** [comment]
@adrisuaDefinitely fantastic news on the grant ! 

I guess it'll depend on whoever would need it more based on their geographic location, their potential contribution to the event, their demonstrated interests, and whether they check off all three requirements. 

I'm trying not to put too many (long) questions in the application, so I'm putting the second question (why do you want to participate in HackSEQ) as an optional content in the additional comment section. I think the geographical location is probably the most important criterion for the travel grant so that's a separate question itself.

**Comment by santina** [comment]
Hi, based on the meeting yesterday ([etherpad](http://pad.software-carpentry.org/hackseq)), we said we want to ask people why they need travel award, as well as adding the option for speaker in the application. 

I have updated [the applicant form](https://docs.google.com/forms/d/19rgCe3vTARspXwUWaOWeOSQJ8wKyl0NhpmIEAtPexNg/viewform) accordingly. Any feedback is welcome.

**Comment by Brittdrog** [comment]
Hi @santina. I think the form looks good. 

Here is some feedback:
- I think "If you're only interested in giving a talk/workshop, you may skip the speaker-specific section" may be worded incorrectly. Maybe it should read "...you may skip **to** the speaker...." 
- I also want to check if you have added a form notification so that participants will get a notification once they submit the form (with links to the website and some basic info about hackseq)?
- You could also consider using the hackseq logo for a background theme (like we did for the team leader applications)

For the travel award section:
- As I understand it the 3 criteria listed are requirements for the ASHG travel funds. As it stands it sounds like these criteria will be used to help us decide who receives the award, but are not requirements. So I would change this by adding the following under the description: "Eligibility: To be eligible for this award, you need to be (i) a trainee (e.g., a graduate student or post-doc), (ii) a member of ASHG and (iii) registered for the 2016 ASHG Meeting in Vancouver"
- I would add a section for the ASHG membership number
- I think we need to add "Other sources of funding and/or other support expected for hackseq/ASHG conference attendance (Agency and amounts)"
-  I would change "Why do you wish to apply for a travel award" to  "As we specifically encourage the participation of women, minorities and individuals from developing countries, please provide a short justification for why you would be a good candidate for a travel award (max 100 words):"

**Comment by santina** [comment]
Hi @Brittdrog , I have made some changes according to your suggestions.  Thank you for pointing those things out! 

One thing I'm not certain about is the last point. We want to prioritize on financial need first and foremost, as discussed in the meeting earlier this week. If we say minorities and developing countries, would we need to specify which groups we consider to be minorities and what countries do we consider developing?

**Comment by minisciencegirl** [comment]
@santina: I don't think we need to. We can create an internal rubric when we are evaluating, but that doesn't need to be spelled out for the application.

**Comment by Brittdrog** [comment]
@santina we could phrase it like the ASHG developing country awards i.e. "developing country as classified by the [World Bank](http://data.worldbank.org/about/country-and-lending-groups) under the low-income and lower-middle income categories."

**Comment by Brittdrog** [comment]
@santina Sorry, I missed your question about the minorities. Maybe we could say something like "Preference will be given to individuals from developing countries (as classified by the World Bank under the low-income and lower-middle income categories) and we encourage the participation of individuals from underrepresented groups, including women and minorities." Then like @minisciencegirl suggested we can create our own rubric based on their justifications.

**Comment by santina** [comment]
Okay thanks! I made the change.

**Comment by sjackman** [comment]
Two issues reported by a participant:

> A couple things for your signup
> · Just in case you care, your sign-up sheet asks to rank your top 3, and then has options for top 4.
> · Also, I broke it :-( If you pick a choice for one project, you can't unpick that project.  And then it gets angry if you try to pick another project.

The second issue, if you click on five projects, there's no way to submit the form. You have to start over from scratch. If possible, a button to clear the project ranking bubbles would be helpful.

**Comment by santina** [comment]
O_O the horror! You're right. You can't unpick the project.  I'm looking into this. Thanks!

**Comment by santina** [comment]
Alright, this is gonna sound messy but should resolve our issue. 

I couldn't find a way to add a button, so my quick solution is transposing the multiple choice and add a text field above the question to list all the projects. The transpose changes the way the output spreadsheet looks, I created a new one call "Hackseq participant Responses" which you have access to with the hackseq account. 

Google form still injects the earlier responses into the new sheet ... so you'd see that the first few responses on the project section match to wrong columns. But don't worry, I already made a copy of the old spreadsheet. I'll take care of all the data cleaning after we close the application. 

Sorry for the embarrassing moment.

**Comment by sjackman** [comment]
No worries. Thanks for the fix. Can you copy the ten project descriptions and their numbers into the form?

**Comment by santina** [comment]
Hi @sjackman , 

Could you clarify what you mean?  Right now the [application form](https://docs.google.com/forms/d/19rgCe3vTARspXwUWaOWeOSQJ8wKyl0NhpmIEAtPexNg/viewform) has a list of 10 projects with their number and titles, there's a link to their descriptions. As shown here. The multiple choice grid scrolls horizontally. 

![image](https://cloud.githubusercontent.com/assets/1039839/16179587/fcbd4a96-361e-11e6-910e-b43aa05163b4.png)

**Comment by sjackman** [comment]
Ack, sorry. I was dumb and didn't see the project titles directly above the multiple choice grid.

**Comment by GalenWright** [comment]
As discussed at the meeting today, here's a draft of the email that we are going to send to potential participants that have sent us their contact details. @brunogrande kindly offered to send them this message tomorrow. Please let us know if there are any edits that you would like us to make before he sends it. Thanks!

Hi there!

Thank you for your interest in [hackseq](http://www.hackseq.com/), the genomics hackathon taking place in Vancouver in October 2016. 

We are excited to announce that we have released the [participant application forms](https://docs.google.com/forms/d/19rgCe3vTARspXwUWaOWeOSQJ8wKyl0NhpmIEAtPexNg/viewform), along with a [list of the projects](https://github.com/hackseq/hackseq_projects_2016/issues) that will be taking part in hackseq! We have a great selection of projects available from diverse backgrounds.

Please fill out [the application form](https://docs.google.com/forms/d/19rgCe3vTARspXwUWaOWeOSQJ8wKyl0NhpmIEAtPexNg/viewform) and select the projects that interest you most by July 15.

Registration is free and the event will take place from October 15-17 (9am-6pm each day) at the UBC Life Sciences Institute, which is on the main campus of the University of British Columbia. Please [click on this link](https://drive.google.com/open?id=1sZaegrYoiuYdD3Ls1Plk7QADPoA&usp=sharing) to see the location of hackseq in relation to the ASHG Meeting, as you may want to stay closer to the UBC campus for the event.

hackseq is a [satellite event](https://www.ashg.org/2016meeting/pages/ancillary.shtml) to the main [ASHG Meeting](http://www.ashg.org/2016meeting/) and we will have three travel awards sponsored by ASHG for trainees (there are more details in the participant application form). 

Regards,
The hackseq organizing committee

**Comment by sjackman** [comment]
Looks good to me! I'd suggest including the 10 project titles in the email with links to each GitHub issue. That could follow your closing salutation.

**Comment by santina** [comment]
@adrisua @ttimbers @minisciencegirl  I added the buttons on our [hackseq website](http://www.hackseq.com/) for links to the application and the project issues.

**Comment by BrunoGrandePhD** [comment]
@GalenWright @sjackman Notification email sent! I included projects titles and links in the email.

**Comment by sjackman** [comment]
Thanks, Bruno!

**Comment by minisciencegirl** [comment]
@santina: how are we doing on the number of participant applications?

I sent out a short & hopefully catchy email to the VanBUG announcement list (and can send another one next week). Do we want to blast UBC/SFU departmental email lists?

**Comment by Brittdrog** [comment]
@minisciencegirl @santina - I just checked the applications and we have 34 people who have signed up.

We also have 86 people who signed up to the interest list (7 of which have applied already). 
I think @GalenWright should email the interest list (those who haven't signed up yet) again on Monday to remind them of the deadline. I will also email the team leaders so that they can remind anyone that they would like to encourage to join their teams.

I think it would be great to email the UBC/SFU department lists too!

**Comment by GalenWright** [comment]
@Brittdrog sure, I'll do that.

The UBC Postdoctoral Association is also going to send out information about the application deadline in their monthly newsletter

**Comment by ttimbers** [comment]
This is great! We are about a week away from the deadline, and worst case scenario we have 34 + 9 team leaders. That makes 43 participants in total, and so that's just under 5 people per team on average. This is a good number for a minimum and we still have some room to grow. Good work team!

**Comment by minisciencegirl** [comment]
@Brittdrog: Thanks!!  I will draft an email and send that out to the UBC/SFU department lists this afternoon.
Also thanks to everyone for retweeting! That's been generating a lot of traffic/ impressions to our Twitter account.
- Update 2016-07-10: also emailed out to various VanBUG partner institutes including the OICR, Compute Canada, Alberta Health, U Calgary, CDRD, BCCDC, U Manitoba and U Montreal. A copy of this email has been sent to the hackseq gmail account.
