### ISSUE TITLE
April Meeting?

### ISSUE THREAD

**Issue by ababaian** [hackseq/October_2016#21]
@hackseq/steering_committee, I know we have a meeting planned for mid-May. Do we want to meet earlier then that for an hour or so to discuss recruitment, promotion and planning for hackseq? Might re-focus us on our next actions, especially for finding Team Leaders.

**Comment by sjackman** [comment]
Liz and I are both in rehearsals right now and so busy, but I'd join if I can.

**Comment by ttimbers** [comment]
Let's try for a Google Hangout meeting - this might be a more realistic option for a quickly scheduled meeting. 

@hackseq/steering_committee members, please fill out the doodle poll link below to find a good time to meet. The meeting will be one hour long. Please try your best sign-up for at least 2 times so that we can find a time when we can all meet.

http://doodle.com/poll/2i59bn3qcxg9ipf2

**Comment by ttimbers** [comment]
@hackseq/steering_committee it is looking like Friday, April 22nd at 10am is the best time for most people. @cloucks @adrisua @brunogrande can you make that date & time? If not, do you mind if we have a short meeting without you?

**Comment by cloucks** [comment]
That works for me! @ttimbers

**Comment by DCGenomics** [comment]
Cant make the meeting, but let me know if there is any way I can help,
besides encouraging folks to apply to be team leads, which I plan to do
later this week/next week.

Cheers!
Ben

**Comment by BrunoGrandePhD** [comment]
I'll be able to make it.

**Comment by BrunoGrandePhD** [comment]
Can someone create an agenda? It would greatly increase the efficiency of the meeting. Unfortunately, I don't have the time to consolidate the various open issues because of my upcoming PhD candidacy exam. 

@ttimbers, as the secretary, do you mind doing this? It's not strictly necessary, but I would rather not have the meeting go on and on like last time.

**Comment by ttimbers** [comment]
@hackseq/steering_committee our next meeting will be on Google Hangouts on Friday, April 22 at 10am, as this is when most of us can meet. Apologies to those who cannot make it. We will take detailed notes and invite you to comment/vote on anything discussed.  The link to the hangout is [here](https://hangouts.google.com/call/fychc5zmkjd6rlbjvfaa37kqyme).

Please add any items that you wish to discuss at the meeting to the [agenda](https://github.com/hackseq/October_2016/blob/master/meeting_notes/2016-04-22_meeting_agenda.md).

**Comment by ttimbers** [comment]
@brunogrande I did this as you wrote the request, great minds think alike :)

**Comment by ttimbers** [comment]
@hackseq/steering_committee please remember to add anything that you want to discuss at tomorrow's meeting to the [agenda](https://github.com/hackseq/October_2016/blob/master/meeting_notes/2016-04-22_meeting_agenda.md).

**Comment by sjackman** [comment]
Good agenda. Thanks, Tiffany.
