### ISSUE TITLE
Volunteers

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#45]
@hackseq/steering_committee Some people have asked me about ways to contribute and we discussed some of the options during our last meeting. I created a form so we can direct people to it and post it on the website [form](https://docs.google.com/forms/d/13eTIH2JWnY3NUC8fpHQT4RedsAaUPx5O2pinGm-gnr0/edit) Please edit it or make comments here. Thanks!

**Comment by BrunoGrandePhD** [comment]
I suggest adding a section for mentors to specify topics they can be mentors for.

**Comment by adrisua** [comment]
@brunogrande would that be an open question? or do you have ideas about specific topics they could help with?

**Comment by BrunoGrandePhD** [comment]
Oh, good point. What about listing the project titles (and link to the longer descriptions on GitHub)?

**Comment by adrisua** [comment]
@hackseq/steering_committee Here are the forms for [mentors](https://docs.google.com/forms/d/18atCF4crckgk4c19r4rDD0P-Vo_TZrVKpILTclQ8ATg/edit) and [volunteers](https://docs.google.com/forms/d/13eTIH2JWnY3NUC8fpHQT4RedsAaUPx5O2pinGm-gnr0/edit). Suggestions will be greatly appreciated (respond by Sunday please).

**Comment by minisciencegirl** [comment]
Both forms look great to me! Let me know when you have the final version and I can tweet the forms and email out to VanBUG list.

**Comment by Brittdrog** [comment]
@adrisua I think the forms look great. I just added form notifications. It may be nice to use the hackseq logo as the header, but not essential.

**Comment by ababaian** [comment]
I spruced up the headers a bit with the 'code' background. Bring it in line with the website a bit better imho.

We should include a statement of what a 'mentor' is and an estimate about time commitment for each Mentor/Volunteer so people know what they're signing up for.

"Mentors are specialists who offer our teams advice and guidance on their projects. Time commitment depend on your interest but we ask for at least one hour of your time."

**Comment by adrisua** [comment]
@ababaian would you mind posting them on the website and let @minisciencegirl know. Thanks!

**Comment by ababaian** [comment]
Done with the volunteer form. Shouldn't we 'invite' for the Mentors?

**Comment by minisciencegirl** [comment]
@ababaian: Maybe we can do both? I will schedule the tweet.

**Comment by ababaian** [comment]
Done

**Comment by BrunoGrandePhD** [comment]
I was about to share the volunteer application form with someone and realized that it requires a Google account because the "Limit to 1 response" option is enabled. I think this unnecessarily limits who can volunteer or mentor at Hackseq. I'm going to disable this option for both forms, because it's easy to remove duplicates afterwards and we haven't imposed this limit so far. If anyone objects, please comment below. 

Also, the links posted above are the edit links, where anyone with the link can request edit access. The links below are those meant for sharing. 
- [Volunteer Application Form](https://goo.gl/forms/fODzG9iWeCczLy0A2)
- [Mentor Application Form](https://goo.gl/forms/yt1JwqUrIxv7t31F2)

**Comment by santina** [comment]
@brunogrande  I fixed the links. Thanks for pointing it out.

**Comment by ttimbers** [comment]
@santina - I have contacted the Vancouver Software Carpentry Community, the UBC R study group, the SFU SciProg group and the UBC MDS students to ask for volunteers to help our participants with any technical issues on the morning of Oct 15th. If any are interested, I directed them to fill out the volunteer form and introduce themselves on the volunteer introduction issue  you opened.

@santina - as you get info from the volunteers, could you please fill out the markdown table below, so we can get an idea of how much help (and extra bodies) we are anticipating? Please only put a single volunteer in one of the two categories, even if they say they can do both things. Thanks!

## Volunteers

| Volunteer task/capabilities | Sat AM | Sat PM | Sun AM | Sun PM | Mon AM | Mon PM |
| --- | --- | --- | --- | --- | --- | --- |
| tech help (e.g., shell, git, AWS, etc) |  |  |  |  |  |  |
| Logistics/organization support |  |  |  |  |  |  |

**Comment by santina** [comment]
@ttimbers  I think we have enough volunteers. I'm gonna close the volunteer form later this week before it gets hard to keep track of everyone. It's great that many people will be helping out!

**Comment by adrisua** [comment]
@santina It would be great to start involving volunteers, specially those interested in helping out with logistics. What do you think would be the best way to ask them? For example, we need help looking for places that rent table throws.

**Comment by santina** [comment]
Idk, should we just add them to the organizer's slack channel? I don't feel like there has to be a distinction between the committee and the volunteers in the slack and GitHub discussion. I have asked them to take a look at the public repo.  

It's better that we can come up with a list of tasks first.  We can open an issue for that first.

**Comment by santina** [comment]
@ttimbers, the volunteer sign-up form doesn't have an option for Monday PM for a list of availabilities, so I'll leave that one blank for now. We can either figure that out at the event or the people who are tagged, feel free to sign up for that slot.  

Most people can do both categories of tasks. Since the first day is likely to be the busiest, it's good that we have many people. 

I'm not super sure how to involve people who want to help prior to the event. I guess one thing is setting up before the start of the event. Or answering questions on slack?

We can also invite people who are in Vancouver to our next meeting, since it'll be at the hackseq venue.

| Volunteer task | Before Event | Sat AM | Sat PM | Sun AM | Sun PM | Mon AM | Mon PM |
| --- | --- | --- | --- | --- | --- | --- | --- |
| tech help (e.g., shell, git, AWS, etc) | @dfornika @lfunderburk @daisieh | @daisieh @zhaoxiaofei @lfunderburk @lstmemery | @irobii @eringill | @lfunderburk @daisieh | @ananab | @daisieh @eringill |  |
| Logistics support | @irobii @eringill @ananab | @Monica-Bui @irobii @eringill @ananab | @LeungConnie @Monica-Bui | @irobii @ananab | @irobii @eringill @LeungConnie | @irobii |  |
| Total | 6 | 9 | 4 | 5 | 5 | 3 | 0 |

This is a tentative assignment. I understand some people's availabilities might have changed. If so, feel free to delete your GitHub handle from dates you're not available. Keep in mind that if you're assigned to one category, doesn't mean you can't do the other. We'll all help out whatever that comes up during the event!

**Comment by lstmemery** [comment]
Do you know what time the shifts start and end?

**Comment by santina** [comment]
Hey @lstmemery, the tentative schedule is here : https://github.com/hackseq/October_2016/blob/master/hackseq_2016_tentative_schedule.md

**Comment by adrisua** [comment]
@irobii @eringill @ananab We need some help with arts and crafts. The goals is to come up with signs (letter size) to acknowledge our sponsors. See more info [here](https://github.com/hackseq/October_2016/issues/63)

**Comment by GalenWright** [comment]
Someone signed up to volunteer yesterday and sent an email to the gmail regarding whether we received their application. @santina could you reply to them and let them know what they could help with (if you think we still could use more volunteers)? Thanks!

**Comment by santina** [comment]
Mmm they should have received an autoreply on what to do next (i.e. check out this repo and respond to the issue).  But sure! In the event if people can't make it, we can still use some help. :)

**Comment by LeungConnie** [comment]
Sorry Santina, I won't be able to help out Sat AM or the Sun AM any longer.

**Comment by santina** [comment]
Hey @LeungConnie no worries, thanks for letting us know.

**Comment by daisieh** [comment]
I can't help on Sun PM, but all of the other slots I'm signed up for are fine.

**Comment by santina** [comment]
I updated the availabilities :)

**Comment by zhaoxiaofei** [comment]
Hi, I might arrive late tomorrow morning. I will be able to stay there until afternoon.

**Comment by radaniba** [comment]
Sorry last minute change in my plans,  wont be able to join you guys :(

**Comment by santina** [comment]
@radaniba for the entire event or just today?  @zhaoxiaofei  Thanks for letting us know!

**Comment by radaniba** [comment]
Entire event :(
Sorry guys, really
