### ISSUE TITLE
Food purchase and pickup responsibilities

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#64]
Lunch: Every lunch is catered. 
Breakfast : 
Coffee from Starbucks 
First need to check Costco pricing for what to bring 

|  | Sat Breakfast | Sat Lunch | Sun Breakfast | Sun Lunch | Mon Breakfast | Mon Lunch |
| --- | --- | --- | --- | --- | --- | --- |
| Items | ----- | ----- | ----- | ----- | ----- | ----- |
| Purchasers | ----- | ----- | ----- | ----- | ----- | ----- |
| Helpers for pickup | ----- | ----- | ----- | ----- | ----- | ----- |

**Comment by BrunoGrandePhD** [comment]
Santina and I got item prices for foodstuff we think are appropriate for a light breakfast and snacks. We also came up with a plan for what to buy for the three days. See the Google Spreadsheet below. 

https://docs.google.com/spreadsheets/d/1DQLlcboxWgMup3e3zbsMZLaeWlcVcSpnj_bKtqtVGTE/edit?usp=sharing

**Comment by adrisua** [comment]
@minisciencegirl @brunogrande Should we split the list? @minisciencegirl maybe you could get the packaged goods and @brunogrande the fruits? 

@brunogrande do you need me to go with you to buy the food or could you go with Santina? 

I will arrange coffee for breakfast

Remember to save your receipts for parking and add them in the reimbursement [form ](https://drive.google.com/file/d/0B4gAe5f4VChNYTBybEVLVGdEOTQ/view)

**Comment by minisciencegirl** [comment]
I added a new column in the Googleform to list the bulky stuff that I can purchase. Are the muffins the giant muffins made by Costco bakery? I can pick those up too. 

@adrisua: Since I will drive in all the bulky stuff, I probably won't meet you at your condo in the morning. However, if someone could meet me at LSI in the morning to help unload, that will be great.

**Comment by adrisua** [comment]
@minisciencegirl Sounds good. What about Sunday and Monday? Since we can't leave stuff at LSI, would you like to do the same each day? Thanks!

**Comment by minisciencegirl** [comment]
@adrisua: No problem. Do you think the baked goods will stay fresh on Monday if I pick things up on Friday? I was thinking of leaving a bit early on Sunday (Costco closes at 5pm) to pick up stuff for Monday. 

@brunogrande: let me know if there's any other bulky item that you want me to pick up from Costco.

**Comment by BrunoGrandePhD** [comment]
Santina and I don't mind doing a Costco run. However, we need to rent a car to buy the stuff from Costco (Modo: ~$8) and then rent another car to bring the stuff to UBC (Evo: ~$16) on Saturday morning (total: ~$24). 

If the organizers are okay with covering the car sharing cost, then Santina and I can go. Otherwise, I can go with @adrisua. What do people think?

Santina also made a good point. It's hard to gauge how much people are going to eat during the event. If Amy is going to do a second Costco run on Sunday night, I recommend we buy all food items for the first two days on the first run, and we adjust the quantity Amy will buy on Sunday based on leftovers.

**Comment by adrisua** [comment]
Great idea. I added the car rental to the budget. Thanks!

**Comment by minisciencegirl** [comment]
Works for me. Thanks @brunogrande and @santina. Also did we budget in the increased number of participants on Monday?

**Comment by GalenWright** [comment]
@minisciencegirl GA4GH have moved to the Marriott, so it's only us

**Comment by BrunoGrandePhD** [comment]
Final setup: Santina and I will do a Costco run on Friday morning and get everything for the first two days. Amy will do a second Costco run Sunday afternoon based on what's left over.
